### ISSUE TITLE
Doesn't build on RC8

### ISSUE THREAD

**Issue by bloomlive** [weicheng2138/nuxt3-eslint-starter#7]
`
user@MBP-2 nuxt3-eslint-starter % yarn build           
yarn run v1.22.19
$ nuxt build
Nuxt CLI v3.0.0-rc.8                                                  13:13:13

 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /Users/user/Code/Experiments/nuxt3-eslint-starter/pages/about.vue?vue&type=script&setup=true&lang.ts&macro=true:24:0
22: const counterStore = useCounterStore()
23: 
24: return (_ctx: any,_cache: any) => {
    ^
25:   const _component_NuxtLink = _resolveComponent("NuxtLink")!

 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
  at Module.tryParse (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12789:25)
  at Module.setSource (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12694:24)
  at ModuleLoader.addModuleSource (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22136:20)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by weicheng2138** [comment]
I do want to check for the new version of nuxt3 rc version. It does update frequently and some of the module like vueuse needs for update, too. Let me check for it.

**Comment by weicheng2138** [comment]
@bloomlive I upgrade dependencies as follow

- nuxt
- @pinia/nuxt
- @vueuse/nuxt
- pinia
- tailwindcss
- prettier-plugin-tailwindcss
- msw
- vitest

The primary problem is the way you import @pinia/nuxt. The problem should be solved.

Note that the warning below
![nuxtrc8](https://user-images.githubusercontent.com/13548635/186054978-160c8a91-ad70-4fa0-8e8f-b90a87082f6f.PNG)
The doc which is provide by nuxt 3 officials is still ambiguous. I'll deal it with later version.
